default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: taskpilot-gpt
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskpilot_gpt_development

test:
  <<: *default
  database: taskpilot_gpt_test

production:
  <<: *default
  database: taskpilot_gpt_production
  username: taskpilot-gpt
  password: <%= ENV['MEUAPP_DATABASE_PASSWORD'] %>
